Create basic visualiser
JamieMair/MuJoCo.jl pull request #17
Opened 2023-08-07 23:02 UTC by nic-barbara

2023-08-07 23:09 UTC, nic-barbara commented
Current status: basic viewer that displays the model, but no interactivity yet. We should try to use the `PhysicsState` type from`LyceumMuJoCoViz.jl` to integrate their default callbacks and handlers into our visualiser. This should be reasonably straightforward once we have nicer array handling on the structs.

2023-08-12 07:57 UTC, JamieMair requested changes
For this PR, I suggest we can commit the files in `vis` (except for `basic.cc`) after some minor tweaks, but we should remove the `lyceum-vis` from this branch and put it in the next PR. You can ignore all the comments on the lyceum code for now, as it will only be useful as a guide for the next PR.

We should probably move to package extensions in the next PR. It doesn't seem too involved. We can follow [this post](https://discourse.julialang.org/t/package-extensions-for-julia-1-9/93397/5) for a guide, and also [the docs](https://pkgdocs.julialang.org/dev/creating-packages/#Conditional-loading-of-code-in-packages-(Extensions)). This should allow us to use `Requires.jl` as well to support people on older versions, before `v1.9`.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
Is this file taken directly from Lyceum? If so, we should credit and attribute in the source code.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
> +end
We should modify this at some point to give clearer instructions.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
Also, we should consider changing the name too, to something like VisualiserExt or just Visualiser

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
> +)
These docs may need some changes

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
> +    p.model isa AbstractMuJoCoEnvironment && (ui.reward = getreward(p.model))
Not a review comment, but what is reward here?

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/glfw.jl
> +#end
Is this commented out for a reason, or just their old source code? Is it worth removing?

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/modes.jl
> +
Where is `EngineMode` defined? Is this an abstract type that can have multiple implementations. In which case, it should likely be called `AbstractEngineMode`.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/modes.jl
> +struct PassiveDynamics <: EngineMode end
Yes, it's abstract

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/modes.jl
> +    dt = @elapsed x.controller(p.model)
We should consider using a function call or functor. Or at least make sure it uses a functor.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/modes.jl
> +    dt = @elapsed x.controller(p.model)
Also, it may be worth creating an `AbstractController` type and define an interface, which would likely be a single function `control` with just the `model` and `data` references? Not sure at this time.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/modes.jl
> +gettraj(m::Trajectory) = m.trajectories[m.k]
This may need some redoing, simply because I am not 100% sure how it works. We also don't have a lot of the internals that this relies on.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/ratetimer.jl
> +LyceumBase.reset!(rt::RateTimer) = (rt.tlast = time_ns(); rt.elapsed = 0; rt)
We don't rely on LyceumBase, perhaps this should be removed?

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/types.jl
> +end
I am not sure if it would be better to wrap these objects so they can be properly GC'd, instead of having to rely on manually freeing. Especially as people operate in the REPL and may run into errors which don't completely crash the program.

I have some ideas on how we can modify this to avoid the need for `Ref` or manual freeing.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/types.jl
> +            rethrow(e)
We should extract this constructor to be outside of the struct definition for clarity.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/util.jl
> +"""
Probably should be removed, or perhaps changed?

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/util.jl
> +end
Probably allocates in `codeunits`? Worth checking if this is in the hot loop for rendering as we want to avoid GC as much as possible.

2023-08-12 07:57 UTC, JamieMair commented on examples/lyceum-vis/util.jl
> +end
We should add FFMPEG as a dep

2023-08-12 07:57 UTC, JamieMair commented on examples/test.jl
Can we remove this? As something similar is in the unit tests?

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/basic.cc
Can be remove this file?

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/glfw.jl
Is this a copy of the original file? Should we go for putting all of the visualisation project together before merging this?

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/glfw.jl
OR - we merge the basic visualisation example now, and remove the lyceum files for a different PR

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/test_vis.jl
> +"""
Definitely worth trying to use as much of their code as possible. I don't think it will be a huge task to port it. Perhaps we should merge only this file for now and move the others to another branch.

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/visualiser.jl
> +    figsensor::Ptr{mjvFigure} = alloc(mjvFigure)
alloc is fine here, but we should add a finaliser to GC the objects since this is a mutable struct.

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/visualiser.jl
> +    # min(map(GetRefreshRate, GLFW.GetMonitors())..., MIN_REFRESHRATE),
Perhaps we can finish these now?

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/visualiser.jl
> +        C_NULL,
Remind me what this C_NULL is again?

2023-08-12 07:57 UTC, JamieMair commented on examples/vis/visualiser.jl
> +    return nothing
This is all great - we should move the frees into the GC.

2023-08-12 07:57 UTC, JamieMair commented on src/MuJoCo.jl
Does this need the `using UnsafeArrays`? 

Also, good idea to validate the path. Perhaps there is a mj function which also validates an `xml` file that we can use? But that's for a separate PR.

2023-08-12 23:27 UTC, nic-barbara commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
Yep for sure, I just copied it in as a reference so I could see which parts would be useful to us.

2023-08-12 23:28 UTC, nic-barbara commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
> +end
Definitely. We might also want to give the user more control over threads, I'll think about how best to implement that.

2023-08-12 23:28 UTC, nic-barbara commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
> +)
Yep, won't be using the original code, just parts of it.

2023-08-12 23:30 UTC, nic-barbara commented on examples/lyceum-vis/LyceumMuJoCoViz.jl
> +    p.model isa AbstractMuJoCoEnvironment && (ui.reward = getreward(p.model))
The way they structured their environments was very similar to `gym`. In these cases, the reward is a function attached to the environment. I'm personally not a fan of this idea, the reward should be nice and configurable by the user. My plan is to take just the visualisation elements and leave the rest.

2023-08-12 23:30 UTC, nic-barbara commented on examples/lyceum-vis/glfw.jl
> +#end
This was commented out in their source code, I haven't touched it. Not sure why.

2023-08-12 23:31 UTC, nic-barbara commented on examples/vis/visualiser.jl
> +    # min(map(GetRefreshRate, GLFW.GetMonitors())..., MIN_REFRESHRATE),
Yep, can do.

2023-08-12 23:31 UTC, nic-barbara commented on examples/vis/visualiser.jl
> +    return nothing
Good point. How do we go about doing that?

2023-08-12 23:32 UTC, nic-barbara commented on src/MuJoCo.jl
Possibly not, I'll check.

2023-08-12 23:33 UTC, nic-barbara commented on examples/vis/visualiser.jl
> +        C_NULL,
Just NULL but in C.

2023-08-13 00:18 UTC, nic-barbara commented on examples/vis/basic.cc
Yes

2023-08-13 00:18 UTC, nic-barbara commented on examples/test.jl
Yes

2023-08-13 08:27 UTC, JamieMair commented on examples/vis/visualiser.jl
> +        C_NULL,
I mean the argument to the function, why are we setting it to null? The function calls it `pert` but I'm not sure what that is.

2023-08-13 08:27 UTC, JamieMair commented on examples/vis/visualiser.jl
> +    return nothing
We should probably wrap these objects in a type just like `Model` and `Data` to make things easier

2023-08-14 02:49 UTC, nic-barbara commented on examples/vis/visualiser.jl
> +        C_NULL,
It's either perturbations to the scene (eg: dragging around the view with the mouse) or perturbations to the environment (eg: due to dragging around objects in the environment). I've set it as null for now because we don't need either of those for the most basic visualiser.

2023-08-14 02:50 UTC, nic-barbara commented on examples/vis/visualiser.jl
> +    return nothing
Agreed. That's happening in https://github.com/JamieMair/MuJoCo.jl/issues/35 right?

2023-08-14 10:13 UTC, merged