Visualiser full lyceum
JamieMair/MuJoCo.jl pull request #40
Opened 2023-08-24 08:09 UTC by nic-barbara

Added in the visualiser from [`LyceumMuJoCoViz.jl`](https://github.com/Lyceum/LyceumMuJoCoViz.jl) as a package extension to our `MuJoCo.jl`. I've tested this on mac and ubuntu - yet to be test on windows at the time of writing.

We currently have feature parity with the old Lyceum visualiser apart from a few key functions:
- They have a function to `reset!()` a MuJoCo environment when the user presses `backspace`. I have excluded this, since resetting is very specific to each model/experiment and doesn't really make sense for a generic MuJoCo model. It made sense in the old visualiser, which used `gym`-like MuJoCo environments.
- I have removed the `Trajectory` mode allowing the user to replay state trajectories through the visualiser. We may want to add this back in later. It relies on the `state` of a MuJoCo model being defined. Again, this makes sense for `gym`-like environments, but not for generic MuJoCo `Model` and `Data` objects.

A few C globals were also required to add button and mouse callbacks. These are currently defined in `ext/VisualiserExt.jl`, but maybe it's better to define them elsewhere. Suggestions would be appreciated :)

2023-08-24 08:10 UTC, nic-barbara commented
This pull request is currently a draft. If I have time in the next day or two, I'll add in the option to apply forces to a model in the visualiser by clicking on it. See [here](https://github.com/rohanpsingh/mujoco-python-viewer) for an example.

2023-08-24 08:12 UTC, nic-barbara commented
There seems to be an issue with `MuJoCo_jll` in the CI, any ideas @JamieMair?

2023-08-24 11:02 UTC, JamieMair commented
> There seems to be an issue with `MuJoCo_jll` in the CI, any ideas @JamieMair?

It's because the MuJoCo_jll package was updated and has a different UUID, I got the same error on my machine and had to remove some cached files in my `.julia` folder. Once the Yggdrasil PR goes in, we can avoid manually pointing to the jll package as it should be registered, which will let us fix the CI error.

2023-08-24 22:50 UTC, nic-barbara commented
> This pull request is currently a draft. If I have time in the next day or two, I'll add in the option to apply forces to a model in the visualiser by clicking on it. See [here](https://github.com/rohanpsingh/mujoco-python-viewer) for an example.

Turns out this is actually already implemented in the original `LyceumMuJoCoViz.jl`, it's just not documented anywhere. Works great. I'll add some documentation on the mouse and button callbacks.

2023-08-27 08:39 UTC, JamieMair requested changes
This is great, we can probably merge this now. I think the trajectory stuff can be postponed until later. I have created some issues for doing just that. I have just removed some of the commented out code in favour of GH issues for todos - see https://github.com/JamieMair/MuJoCo.jl/pull/44

2023-08-27 08:39 UTC, JamieMair commented on ext/VisualiserExt/VisualiserExt.jl
> +
It took me a while to understand what this is doing, but yes, this is completely fine. I've moved this part to another file for clarity.

2023-08-27 08:39 UTC, JamieMair commented on ext/VisualiserExt/modes.jl
> +####
I have created https://github.com/JamieMair/MuJoCo.jl/issues/41 to keep track of this, and removed the commented out code for now in my branch of this pr

2023-08-27 08:39 UTC, JamieMair commented on ext/VisualiserExt/VisualiserExt.jl
> +    # data.qvel .= @SVector [0.01, 0]
Removed commented code in my branch

2023-08-27 22:47 UTC, merged